name: omxplayer_video_player
description: A package that implements video_player_platform_interface using omxplayer and platform views.
version: 2.1.1
homepage: https://ardera.dev
repository: https://github.com/ardera/flutter_packages
resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  video_player_platform_interface: ^6.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
