name: flutter_gpiod
description:
  Dart package for accessing GPIO using the GPIO character device interface on linux / Android (root required).
  Supports signal edge listening, active state, open source/drain and (if supported by platform) bias.
version: 0.5.1+5
homepage: https://ardera.dev/
repository: https://github.com/ardera/flutter_packages
   
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  ffi: ^2.0.1
