name: _ardera_libc_bindings_generator
description: A dart:ffi bindings generator for libc.
version: 0.1.1+1
repository: https://github.com/ardera/flutter_packages
resolution: workspace

dependencies:
  ffigen: ^11.0.0
  ffi: ^2.0.1
  async: ^2.5.0
  convert: ^3.0.0
  crypto: ^3.0.1
  path: ^1.8.0
  logging: ^1.0.1
  source_gen: ^1.0.0
  analyzer: ^6.4.1
  win32: ^5.5.0
  xdg_directories: ^1.0.4
  dart_style: ^2.0.0
  build: ^2.2.1
  yaml: ^3.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'