name: linux_spidev
description: Dart package for accessing SPI on Linux using the spidev interface and dart:ffi.
version: 0.2.1+5
homepage: https://ardera.dev
repository: https://github.com/ardera/flutter_packages

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ffi: ^2.0.0
  meta: ^1.1.8
  tuple: ^2.0.0
  path: ^1.7.0
  _ardera_common_libc_bindings: ^0.3.2
