name: _ardera_common_libc_bindings
description: |
  Some common libc bindings. (ioctl, gpio, stuff like that)
  
version: 0.0.1
repository: https://github.com/ardera/flutter_packages/

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  _ardera_libc_bindings_generator:
    path: ../_ardera_libc_bindings_generator
    
dependencies: 
  build_runner: ^2.1.7
  ffi: ^1.1.2
