name: flutterpi_gstreamer_video_player_example
description: Demonstrates how to use the flutterpi_gstreamer_video_player plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutterpi_gstreamer_video_player:
    path: ../

  cupertino_icons: ^1.0.2
  video_player: ^2.7.0
  chewie: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
