name: _ardera_libc_bindings_generator_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.4
  _ardera_libc_bindings_generator:
    path: ../
  pedantic: ^1.10.0
