name: flutterpi_gstreamer_video_player
description: video_player platform implementation for flutter-pi.
version: 0.1.1+1
repository: https://github.com/ardera/flutter_packages

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  video_player: ^2.4.10
  video_player_platform_interface: ">=5.1.1 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # none of the official platforms are supported.
  plugin:
    platforms: {}
